version: 2.1

jobs:
  run-crd:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y wget curl unzip xvfb x11-utils gnupg2 software-properties-common

      - run:
          name: Install Google Chrome
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome*.deb || sudo apt --fix-broken install -y
            rm google-chrome*.deb

      - run:
          name: Install Chrome Remote Desktop
          command: |
            wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
            sudo dpkg -i chrome-remote-desktop*.deb || sudo apt --fix-broken install -y
            rm chrome-remote-desktop*.deb

      - run:
          name: Setup CRD user
          command: |
            sudo useradd -m chromeuser
            sudo usermod -a -G chrome-remote-desktop chromeuser
            echo "exec /usr/bin/xfce4-session" | sudo tee /home/chromeuser/.chrome-remote-desktop-session
            sudo chown chromeuser:chromeuser /home/chromeuser/.chrome-remote-desktop-session
            sudo apt install -y xfce4 desktop-base xscreensaver

      - run:
          name: Start Chrome Remote Desktop
          command: |
            CRD_COMMAND='/opt/google/chrome-remote-desktop/start-host \
              --code="4/0AUJR-x6sA9IJleILIEmL9iwj-VhDQW9FefNgDexrVEHqnfhSRH5a5FQ8Pm8t8GSrGkivEw" \
              --redirect-url="https://remotedesktop.google.com/_/oauthredirect" \
              --name=$(hostname) \
              --pin=123456 \
              --user-name=chromeuser'

            echo "Menjalankan Chrome Remote Desktop..."
            sudo bash -c "$CRD_COMMAND"

      - run:
          name: Keep alive for 10 hours
          command: |
            echo "Mesin tetap hidup selama 10 jam..."
            sleep 36000

workflows:
  version: 2
  crd-workflow:
    jobs:
      - run-crd
