version: 2.1

parameters:
  crd_code:
    type: string
    default: ""

jobs:
  setup-crd:
    executor:
      name: win/default
    steps:
      - checkout

      - run:
          name: Install Chrome Remote Desktop
          shell: powershell.exe
          command: |
            Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chrome-remote-desktop.msi"
            Start-Process -FilePath "msiexec.exe" -ArgumentList "/i chrome-remote-desktop.msi /quiet /norestart" -Wait
            Remove-Item -Path "chrome-remote-desktop.msi"

      - run:
          name: Configure Chrome Remote Desktop
          shell: powershell.exe
          command: |
            $PIN = "123456"  # Ganti dengan PIN CRD kamu
            $CRDCode = "<< pipeline.parameters.crd_code >>"
            & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" `
              --code=$CRDCode `
              --redirect-url="https://remotedesktop.google.com/_/oauthredirect" `
              --name=$Env:COMPUTERNAME `
              --pin=$PIN

      - run:
          name: Delay for 10 hours
          shell: powershell.exe
          command: Start-Sleep -Seconds 36000

      - run:
          name: Display Completion Message
          shell: bash
          command: echo "Chrome Remote Desktop setup complete. Access it at https://remotedesktop.google.com/access"

workflows:
  version: 2
  crd_workflow:
    jobs:
      - setup-crd:
          crd_code: << pipeline.parameters.crd_code >>
