version: 2.1

executors:
  windows-executor:
    docker:
      - image: mcr.microsoft.com/windows/servercore:ltsc2022
    working_directory: C:/project

jobs:
  run-crd:
    executor: windows-executor
    steps:
      - run:
          name: Install dependencies
          command: |
            choco install wget curl unzip
            choco install googlechrome
            choco install chrome-remote-desktop

      - run:
          name: Setup Chrome Remote Desktop user
          command: |
            # Create user
            net user chromeuser /add
            net localgroup "Remote Desktop Users" chromeuser /add
            net localgroup Administrators chromeuser /add

            # Setup Chrome Remote Desktop
            echo "exec /usr/bin/xfce4-session" > C:/Users/chromeuser/.chrome-remote-desktop-session
            chown chromeuser:chromeuser C:/Users/chromeuser/.chrome-remote-desktop-session

      - run:
          name: Start Chrome Remote Desktop
          command: |
            # Set up CRD with your code and pin
            set CRD_COMMAND=C:/Program Files (x86)/Chrome Remote Desktop/start-host.exe ^
              --code="4/0Ab_5qllF5ZnT5Zl-StV19Kor_Q4Emlf7a_6JXDINEjOX9YEU4FGric0B1YiSfR5kfKMDGw" ^
              --redirect-url="https://remotedesktop.google.com/_/oauthredirect" ^
              --name=$(hostname) ^
              --pin=123456 ^
              --user-name=chromeuser

            echo "Running Chrome Remote Desktop..."
            start "" /B %CRD_COMMAND%

      - run:
          name: Keep alive for 10 hours
          command: |
            echo "Keeping machine alive for 10 hours..."
            timeout /t 36000

workflows:
  version: 2
  crd-workflow:
    jobs:
      - run-crd
